### ISSUE TITLE
EntryTransactionDetail AmtDtls

### ISSUE THREAD

**Issue by ronnievisser** [genkgo/camt#10]
Hi,

Is there a reason why AmtDtls aren't available within a transaction detail???

**Comment by frederikbosch** [comment]
@RonnieVisser Nope. Maybe because nope needed it yet. You can contribute if you'd like!

**Comment by antlih** [comment]
Ronnie did you look in to this? I would need the AmtDtls as well.

**Comment by ronnievisser** [comment]
No I haven't yet. probably soon.

**Comment by antlih** [comment]
I think I managed to add it, will commit soon.

**Comment by ronnievisser** [comment]
Ok cool! Saves me some time :)

**Comment by PowerKiKi** [comment]
Fixed in #39
