### ISSUE TITLE
How to get owner and Financial institution information?

### ISSUE THREAD

**Issue by binaryhq** [genkgo/camt#105]
Hi there,

Is there any way yo get owner and financial institution details of an account? [053.v4]

https://github.com/genkgo/camt/blob/0ea252af563e3e04119845a7e7e9093a886de945/test/Unit/Camt053/Stubs/camt053.v4.xml#L44-L61

Thanks

**Comment by PowerKiKi** [comment]
I don't think there is a way to get that. If you submit a PR that is covered by unit tests, it could get merged though.
