### ISSUE TITLE
Cannot parse "-1,2" to Money

### ISSUE THREAD

**Issue by wildtierschweiz** [genkgo/camt#107]
Hi, Thanks for this library it is very useful!

I experience an issue with the MoneyFactory, in conjunction with phpmoney\money.

https://github.com/genkgo/camt/blob/0ea252af563e3e04119845a7e7e9093a886de945/src/Util/MoneyFactory.php#L30

It converts 'DBIT' indicators to negative amounts, but somehow theres a subsequent issue with 
Money\Parser\DecimalMoneyParser:

```
Cannot parse "-1,2" to Money. [C:\xampp\htdocs\domain3.local\vendor\moneyphp\money\src\Parser\DecimalMoneyParser.php:68]

[C:/xampp/htdocs/domain3.local/vendor/genkgo/camt/src/Util/MoneyFactory.php:35] Money\Parser\DecimalMoneyParser->parse('-1,2',MoneyCurrency::__set_state([]))
```

There is infact a 'DBIT' entry in my camt with amount 1.20 (CHF)
But I can't find out what's the problem here.

Thanks!

**Comment by wildtierschweiz** [comment]
Ok, I found, that it works on the live system.
Must be something to my local system's locale ...

**Comment by PowerKiKi** [comment]
Can you please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/minimal-reproducible-example) of code that exhibits this issue without relying on an external file, and with a manually set locale ?

And don't forget to mention what version of PHP you are using.

**Comment by wildtierschweiz** [comment]
Hi, I can not reproduce it isolated. It works fine without external files.

PHP: 7.4
OS: Windows 10

It's within the context of the FatFreeFramework 3.7.3 where it happens.
If I setlocal('ch'); before the camt parsing in the page controller it works.

closed.
