### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by huebner-t** [genkgo/camt#118]
Hello,

I get some deprecation messages at php 8.1:

`Deprecated: Return type of Money\Currencies\ISOCurrencies::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/moneyphp/money/src/Currencies/ISOCurrencies.php on line 64

Deprecated: Return type of Money\Currency::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/moneyphp/money/src/Currency.php on line 86

Deprecated: Return type of Money\Money::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/moneyphp/money/src/Money.php on line 521`

Kind regards,
Tobias

**Comment by frederikbosch** [comment]
Which version of Money do you have installed? I guess it its version 3. For PHP 8.1 compatibility you need version 4.
