### ISSUE TITLE
Cannot parse "00000000000XXXX.XX" to Money

### ISSUE THREAD

**Issue by nssnl** [genkgo/camt#122]
Recently upgraded to 2.3 (coming from 0.6.0).
I tested with CAMT.053.001.02 files of NL ING and NL ABN - both files give no issues with 0.6.0. For NL ING also no issues with 2.3, but with NL ABN, getting the following error:

`Cannot parse "000000000005202.96" to Money`

The `Amt` entries in the XML all having leading zero's. The first entry is:
`<Amt Ccy="EUR">000000000005202.96</Amt>`

When, for testing purposes, I remove the leading zero's of all `Amt` entries, there are no issues. Anybody else has experienced this issue?

**Comment by nssnl** [comment]
Found a way to fix this, by removing the leading zero's in /src/Util/MoneyFactory.php

Added below line 27 (`$amount = (string) $xmlAmount;`):
`$amount = ltrim($amount, "0");`

I'll create at PR

**Comment by PowerKiKi** [comment]
Will be fixed via https://github.com/moneyphp/money/pull/702
