### ISSUE TITLE
Add support for `camt.054.001.08`

### ISSUE THREAD

**Issue by PowerKiKi** [genkgo/camt#126]
Following https://github.com/genkgo/camt/pull/124 we need to add support for `camt.054.001.08`.

I expect to be able to support new versions side-by-side in a minor release, as we already do for `camt.054.001.02` and `camt.054.001.04`.

~If anybody has time for it, PR are welcome.~

**Comment by timyyo** [comment]
Is there an estimate for this issue? I would be willing to sponsor an implementation of this extension.

**Comment by PowerKiKi** [comment]
@timyyo I could not find a way to contact you privately. But if you contact me first, I'll send you an estimate for it. My email address is my GitHub username at gmail.com

**Comment by PowerKiKi** [comment]
We reached an agreement, and I'll be doing that in the coming days.
