### ISSUE TITLE
Add support for `camt.053.001.08`

### ISSUE THREAD

**Issue by GuppyDD** [genkgo/camt#142]
Following #124 support for `camt.053.001.08` would be nice.

> Seit November 2021 bietet die Deutsche Kreditwirtschaft (DK) die elektronischen Kontoinformationen (camt.052, 053 und 054) auf Basis der ISO 20022-Version 2019 an.
> Dies sind die Formatversionen `camt.052.001.08`, `camt.053.001.08` bzw. `camt.054.001.08`.

Google Translation:
> Since November 2021, the German banking industry (DK) has been offering electronic account information (camt.052, 053 and 054) based on ISO 20022 version 2019.
> These are the format versions `camt.052.001.08`, `camt.053.001.08` and `camt.054.001.08`.

https://www.ebics.de/securedl/sdl-eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2Nzk5NzYwODgsImV4cCI6MTY4MDA2NjA4OCwidXNlciI6MCwiZ3JvdXBzIjpbMCwtMV0sImZpbGUiOiJmaWxlYWRtaW5cL3Vuc2VjdXJlZFwvYW5sYWdlM1wvYW5sYWdlM19zcGVjXC9BbmxhZ2VfM19EYXRlbmZvcm1hdGVfMy42LnBkZiIsInBhZ2UiOjEwM30.svnVwbw7Z0dTLRO7nPCVT8_nboYQXf4YKGBbWfXZwbE/Anlage_3_Datenformate_3.6.pdf

> All ISO 20022 standard-based XML payment messages specified under the four 2023 Single Euro payments area ( ) payment scheme rulebooks entering into force on 19 November 2023 will be based on the 2019 version of the ISO 20022 standard. This migration to the 2019 version by November 2023 results from a decision taken by the back in September 2020.
https://www.europeanpaymentscouncil.eu/document-library/guidance-documents/guidance-migration-2019-version-iso-20022-based-xml-messaging

Download of the new camt.05X Version 2019 (Version 08) specifications:
https://www.ebics.de/securedl/sdl-eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2Nzk5ODk5NDksImV4cCI6MTY4MDA3OTk0OSwidXNlciI6MiwiZ3JvdXBzIjpbMCwtMiwyXSwiZmlsZSI6ImZpbGVhZG1pblwvdW5zZWN1cmVkXC9hbmxhZ2UzXC9hbmxhZ2UzX2NhbXRcL0lTTy1TY2hlbWFjYW10MDV4X1ZlcnNpb25fMjAxOS56aXAiLCJwYWdlIjoxMDV9._Kh0iq0zKGQv_E7X9BAdfpBvGMzFaTBwjam0oYjYpKA/ISO-Schemacamt05x_Version_2019.zip

**Comment by PowerKiKi** [comment]
This is not something I plan to implement myself (unless somebody is willing to sponsor), so PRs, covered by tests, are welcome.

**Comment by sbuerk** [comment]
Working on it ...

**Comment by PowerKiKi** [comment]
@sbuerk, regarding your " investigate if new entity classes and properties must be added". In my recent #138, I only provided equivalent reading support for the new version. I did not add every single me things that could be read from the new version. The reasoning being that those could be added later when somebody has an actual need for it.

So for your work feel free to do the same. Provide similar reading features than old version, and only add new class/properties if you have an actual need for it.

**Comment by GuppyDD** [comment]
Ich kehre zurück am 17.04.2023.

Sehr geehrte Damen und Herren,

vielen Dank für Ihre Nachricht. Derzeit befinde ich mich nicht im Büro, bin
jedoch ab dem 17.04.2023 wieder persönlich für Sie erreichbar. Ihre E-Mail
wird nicht weitergeleitet.

In dringenden Fällen wenden Sie sich bitte an meinen Kollegen Herrn Marcus
Kupke ***@***.***) oder die Zentrale unter: 0351 810 77 33, die Ihr
Anliegen an die entsprechende Fachabteilung weiterleiten wird.

Mit freundlichen Grüßen
Marco Gubisch


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[genkgo/camt] Add support for `camt.053.001.08` (Issue #142)" gesendet am
12.04.2023 13:51:16.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by GuppyDD** [comment]
Ich kehre zurück am 17.04.2023.

Sehr geehrte Damen und Herren,

vielen Dank für Ihre Nachricht. Derzeit befinde ich mich nicht im Büro, bin
jedoch ab dem 17.04.2023 wieder persönlich für Sie erreichbar. Ihre E-Mail
wird nicht weitergeleitet.

In dringenden Fällen wenden Sie sich bitte an meinen Kollegen Herrn Marcus
Kupke ***@***.***) oder die Zentrale unter: 0351 810 77 33, die Ihr
Anliegen an die entsprechende Fachabteilung weiterleiten wird.

Mit freundlichen Grüßen
Marco Gubisch


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[genkgo/camt] Add support for `camt.053.001.08` (Issue #142)" gesendet am
12.04.2023 15:48:34.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by GuppyDD** [comment]
Ich kehre zurück am 17.04.2023.

Sehr geehrte Damen und Herren,

vielen Dank für Ihre Nachricht. Derzeit befinde ich mich nicht im Büro, bin
jedoch ab dem 17.04.2023 wieder persönlich für Sie erreichbar. Ihre E-Mail
wird nicht weitergeleitet.

In dringenden Fällen wenden Sie sich bitte an meinen Kollegen Herrn Marcus
Kupke ***@***.***) oder die Zentrale unter: 0351 810 77 33, die Ihr
Anliegen an die entsprechende Fachabteilung weiterleiten wird.

Mit freundlichen Grüßen
Marco Gubisch


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[genkgo/camt] Add support for `camt.053.001.08` (Issue #142)" gesendet am
12.04.2023 15:03:51.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.
