### ISSUE TITLE
Fix Codecov integration

### ISSUE THREAD

**Issue by PowerKiKi** [genkgo/camt#149]
@frederikbosch could you please  fix Codecov integration as the mention themselves:

> :exclamation: Your organization is not using the GitHub App Integration. As a result you may experience degraded service beginning May 15th. Please [install the Github App Integration](https://github.com/apps/codecov) for your organization. [Read more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=None).

And also in the repository settings, remove the check for Scrutinizer. We decided to remove it a while ago, but GitHub still thinks it should happen:

![image](https://github.com/genkgo/camt/assets/72603/22b77ea5-97ff-4936-8ab8-8cd3f943c765)

**Comment by frederikbosch** [comment]
This should be done.
