### ISSUE TITLE
Other account identification

### ISSUE THREAD

**Issue by Einenlum** [genkgo/camt#15]
It seems IBAN is not the only way of identification of an account, in camt 053.

https://www.iso20022.org/standardsrepository/public/wqt/Content/mx/dico/mc/_Pdwzodp-Ed-ak6NoX_4Aeg_-1833658219

It can be replaced by another identification of type *GenericAccountIdentification1*, containing:

* a *Identification* string
* a *SchemeName* (containing a *Code* or a *Proprietary*)
* an *Issuer* string.

I'm not sure how to handle this.
* Do you think we should create a base Account DTO (with maybe a *getIdentifier()* method returning IBAN or a concat of GenericAccountIdentification informations) and two children ?
* Or maybe just add these informations in the same DTO as we have now, so it could have an Iban, an Identification, a SchemeName and an Issuer?

**Comment by frederikbosch** [comment]
I believe this one is resolved.
