### ISSUE TITLE
Add an option to disable validator

### ISSUE THREAD

**Issue by Einenlum** [genkgo/camt#18]
Unfortunately, it seems some banks can send Camt files not respecting entirely the XSD.

Found in [this PDF](http://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/implementation-guidelines-camt.pdf):

> For the Swiss ISO 20022 Payments Standard, no special XML schemas will be issued for the "camt.052", "camt.053" and "camt.054" messages, in contrast to the messages for Credit Transfers (pain.001), Direct Debits (pain.008) and Status Reports (pain.002). The messages from Swiss financial institutions therefore correspond to the ISO standard, but do not use it in its entirety.

If I understand correctly, some Camt messages can be validate for banks but not following XSD… Therefore, shouldn't we be able to add an option to deactivate validator while reading and parsing the file?

**Comment by frederikbosch** [comment]
We could move the validation from the `Decoder` into a `Validator` which we call from the Reader if a config `validate` is `true`, which should be the case by default.

**Comment by tijuan** [comment]
It seems no one is working on that one. I will provide a PR very soon.

**Comment by frederikbosch** [comment]
Cool.

**Comment by tijuan** [comment]
PR waiting. Thanks ;)

**Comment by tijuan** [comment]
@frederikbosch Do you have a few minutes to review my PR please ?  
Regards.

**Comment by MrMoronIV** [comment]
Bank example files are not validating, although they are official bank files, hence this option is a requirement to make things work. I assume this PR has never been pulled and this options is thus still missing?
