### ISSUE TITLE
Bug in readme(?)

### ISSUE THREAD

**Issue by Vinze** [genkgo/camt#33]
The readme gives the following example:

```
$statements = $message->getRecords();
```

When executing the I got the following error: `Call to undefined method Genkgo\Camt\Camt053\Message::getRecords()`.

I'm guessing this is a typo and it needs to be `$message->getStatements();`. Is that the correct method?

Also, is it possible to get the parsed output as an array or json?

**Comment by frederikbosch** [comment]
There have been a lot of changes, due to the support of additional message formats (which is great). I need to give this repo a comprehensive review and update the readme. When this will happen, I cannot tell. Please try to figure out yourself in the meanwhile, sorry for that.

**Comment by Vinze** [comment]
Alright, thanks for the quick reply!

**Comment by Einenlum** [comment]
@Vinze Could you precise the version you're using? It seems `Genkgo\Camt\Camt053\Message` does not longer exist in the current version.
