### ISSUE TITLE
Date time issue

### ISSUE THREAD

**Issue by ronnievisser** [genkgo/camt#34]
Hi,

I have camt053 files from triodos bank that has an extra .999999 behind the dates in the files. If I'm correct this is some oracle format. The datetimeimmutable fails on this. Any ideas how to solve other then editing the file before parsing it?

Thnx

**Comment by frederikbosch** [comment]
Maybe we can initialize a DateTimeImmutable using its createFromFormat sentence? Is PHP capable in initializing this date format at all?

**Comment by ronnievisser** [comment]
It seems that it are microseconds. It also only the case in the Stmt.ToDtTm node.

I know that Carbon can handle it with the 
```php
Carbon::parse
``` method

I will take a look at the impact to implement it.

**Comment by ronnievisser** [comment]
Seems that DateTimeImmutable can handle microseconds up to 6 digits. mine has 9.

**Comment by frederikbosch** [comment]
@ronnievisser In that case something to this might work
```php
DateTimeImmutable::createFromFormat('Y-m-d\TH:i:s.u\Z');
```

**Comment by frederikbosch** [comment]
The `u` is for microseconds.

**Comment by frederikbosch** [comment]
@ronnievisser Okay, that is a pity. Does that Triodos CAMT file has some kind of signature? Is it recognizable as a Triodos CAMT file? We might want to create abstractions per different camt file.

**Comment by ronnievisser** [comment]
php can't handle nanoseconds only microseconds.. so I have to replace it in the file first before handling it.

There is no signature to recognize it a triodos I'm afraid. maybe the naming convention of the file but I'm not sure.
