### ISSUE TITLE
any plans to update money dependency?

### ISSUE THREAD

**Issue by ronnievisser** [genkgo/camt#35]
Hi,

Do you have any plans to upgrade the Money dependency? to for example 3.0 or 1.3?

**Comment by frederikbosch** [comment]
@ronnievisser I am team member of `Money`. We are about to publish a stable version of `Money`. When the stable is released I will implement it here and give this library a thorough review too.

**Comment by ronnievisser** [comment]
ok! any ETA on that?

**Comment by frederikbosch** [comment]
Nope. We are working on it for months already.
https://github.com/moneyphp/money/issues/174
