### ISSUE TITLE
Bug related to handling of <Ustrd> and <Strd>?

### ISSUE THREAD

**Issue by antlih** [genkgo/camt#36]
I'm still investigating, but for me it looks like if `<Ustrd>` is present then the <Strd> information is not handled properly. I have couple of cases having both unstructured information (i.e. free text of max 140 chars) and Reference number (Strd->CdtrRefInf->Ref). In this case only Ustrd is available, if I remove the tag then the reference is available as it should.

**Comment by frederikbosch** [comment]
Maybe it is, see these lines
- [Check for Unstructured](https://github.com/genkgo/camt/blob/478aa0a0691240c2c76d3b16282da1c80d9c79f0/src/Decoder/EntryTransactionDetail.php#L133)
- [Check for Structured](https://github.com/genkgo/camt/blob/478aa0a0691240c2c76d3b16282da1c80d9c79f0/src/Decoder/EntryTransactionDetail.php#L142)

As both if statements return, there cannot be both a structured and unstructured now. Please PR to fix.

**Comment by antlih** [comment]
Ok, I got it fixed. I will make a pull request for this and handling of AmtDtls. It should happen early next week at latest (have to finish something first).

**Comment by PowerKiKi** [comment]
This should hopefully be fixed by #59.
