### ISSUE TITLE
Handling of the CdtDbtInd and Amt information

### ISSUE THREAD

**Issue by antlih** [genkgo/camt#38]
Hello,

I'm just raising a question about handling the CdtDbtInd and Amt values. Now the library does the work for you by checking CdtDbtInd and in case of DBIT the Amt is multiplied by -1. I see this may cut some corners when saving the values for further use (e.g. to database) so you don't have to consider the transfer direction. My question is should this be handled instead so that provide the user a method to get the CdtDbtInd and Amt values as they are and remove the "logic" from the library and implement it just towards the standard (and act as a pure parser)? 

p.s. fantastic job from all the contributors, this library has saved a lot of time for me. I'm trying my best to participate.

**Comment by frederikbosch** [comment]
@antlih I dont completely understand the problem. Why is saving the amount a problem? You can create an integer (or decimal) column in your database, right? If you want that to accept negative amounts you should not make that column unsigned.

**Comment by antlih** [comment]
Surely it is not a big problem, more like a philosophical question if the mentioned logic should or should not be part of a data parser. As a maintainer you decide that of course and I respect your decision.

As an example, I have a case in my hand where I need to just parse and save the (selected) data to the database, including the CdtDbtInd value as it is. I have to "decode" the library logic back by checking if the amount is negative or not and then define the value. 

Regardless the AmtDtls->TxAmt->Amt need to be processed similarly.

**Comment by frederikbosch** [comment]
Well, the library's intention are bigger than just parsing. By using `Money` you can actually do comparison of the amounts. That would not be possible if an amount would be a float. Because of floating point precision problem, I never use float/decimal any more for amounts. See problems below. Try to execute it with PHP and see for yourself. That is why I am using `Money`.

```
$x = 8 - 6.4;
$y = 1.6;
$x == $y; // false
$x === $y; // false
(string) $x === (string) $y; // true
```
