### ISSUE TITLE
BankToCustomerStatementV03 support (camt.053.001.03)

### ISSUE THREAD

**Issue by jonaswouters** [genkgo/camt#4]
Hey @frederikbosch 
What did you have in mind for supporting different versions of the Camt053 format?
 
A new Camt05300103 folder next to the existing Camt053 folder which would serve as a base for all Camt053 versions? 

PS, where did you get the XSD file for the camt.053.001.02 format? I can't seem to find it for the camt.053.001.03 format. 

Thanks

**Comment by frederikbosch** [comment]
@jonaswouters In the library I left room for multiple formats by interfacing the decoder and using a [`MessageFormatInterface`](https://github.com/genkgo/camt/blob/master/src/Camt053/MessageFormat.php). By using the `Config` class, [other message formats can be added](https://github.com/genkgo/camt/blob/master/src/Config.php#L22). If you could help in this matter, that would be wonderful.

So, my idea is to add all CAMT formats. I also read there are other CAMT formats than 053. If people need them, we might add them. 

Regarding the XSD: frankly, I don't remember. I believe I downloaded it from some ISO website.

**Comment by frederikbosch** [comment]
https://www.iso20022.org/message_archive.page

**Comment by frederikbosch** [comment]
Since I have no idea what has changed in the specific versions, we should think on how to share code between the versions. Make we can create classes like `MessageFormatV02` vs MessageFormatV03` and `DecoderV02 vs DecoderV03`. And those objects share the same value objects. But maybe it is better to move every format to its own namespace. That would depend on the amount of changes. Regarding the 

Anyway, it is likely this will introduce BC breaks, which is fine. We will then upgrade to `0.2.0`.

**Comment by jonaswouters** [comment]
Comparing the 2 xsd files show only a limited number of additions. Nothing that seems to break backwards compatibility. There are a few new fields, so in my opinion, extending on the previous version seems most logical. 

I'm going to implement it that way for now and do a PR in a few

**Comment by frederikbosch** [comment]
@jonaswouters Sounds great. We still need two instances of the `MessageFormat` to indicate which which message format is supported. So I guess `MessageFormatV02` vs `MessageFormatV03` will still be required, which means BC break, and therefore an upgrade to `0.2.0`. Anyway, it would be a great addition.

**Comment by jonaswouters** [comment]
@frederikbosch so you agree with the file structure of the PR I created? Feel free to suggest a different structure.

**Comment by frederikbosch** [comment]
@jonaswouters I did change the structure. Since we are on 0.1.0, there is no need to be backward compatible. I think now the structure now allows any new version of CAMT 053.

**Comment by frederikbosch** [comment]
Regarding the precision, I do not get why we need to round and/or convert to float? This is what `Money` should take care of. Could you tell me why that specific line needs to be changed?

**Comment by jonaswouters** [comment]
See my comment https://github.com/genkgo/camt/commit/d925c6349ab6323b68540cf9223db50efff51b7f#commitcomment-13517814

KBC belgium provides the camt053.001.03 file with 3 decimal points.
102.850 instead of 102.85

The money libary only allows up to 2 decimals. 
The camt053 standard allows up to 5 decimals

**Comment by frederikbosch** [comment]
@jonaswouters Lets move the precision discussion to this issue. If I am correct, you do not care about the additional decimal points, but now it prevents your document to be decoded to an camt message, right?

Then I would say, we grab the `stringToUnits` method from Money and modify it as such that it allows up to 5 decimal points as argument, but returns an int where the last digit is removed. I think we should [avoid `float` at all cost](https://github.com/mathiasverraes/money).

**Comment by jonaswouters** [comment]
@frederikbosch sounds good! That works for me.

**Comment by frederikbosch** [comment]
And of course, we should include the credits to the Money library when we copy the method.

**Comment by frederikbosch** [comment]
@jonaswouters Can you create a PR which is based on the current master and includes a test?

**Comment by jonaswouters** [comment]
@frederikbosch what should the PR include? A test for camt053 v3 or for the 3 decimal thing?

**Comment by frederikbosch** [comment]
@jonaswouters Both is best of course, but a test for the *5* decimal thing should be there.

**Comment by jonaswouters** [comment]
@frederikbosch created PR, if you have the time could you adjust the regex? I could not get it to work right away. Out of time for today.

**Comment by frederikbosch** [comment]
Fixed and merged, thanks for your contribution!

**Comment by frederikbosch** [comment]
Also tagged `0.2.0`.

**Comment by frederikbosch** [comment]
Added extra tests for additional decimals. Now remaining decimals are correctly discarded. Tagged `0.2.1` with the fixes.

**Comment by jonaswouters** [comment]
Thanks for the help! All my project tests are passing now.
