### ISSUE TITLE
Parsing STUZZA issue

### ISSUE THREAD

**Issue by sreisenb14** [genkgo/camt#41]
i would like to parse my Stuzza files, this are basically simple camt.053.001.02 files, the header looks like this:

`<?xml version="1.0" encoding="UTF-8"?><Document xmlns="ISO:camt.053.001.02:APC:STUZZA:payments:003" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

when running the script, it returns:

`PHP Fatal error:  Uncaught exception 'Genkgo\Camt\Exception\ReaderException' with message 'Unsupported format, cannot find message format with xmlns ISO:camt.053.001.02:APC:STUZZA:payments:003' in /opt/company/finance/banking/scripts/vendor/genkgo/camt/src/Reader.php:94
Stack trace:
#0 /opt/company/finance/banking/scripts/vendor/genkgo/camt/src/Reader.php(38): Genkgo\Camt\Reader->getMessageFormatForXmlNs('ISO:camt.053.00...')
#1 /opt/company/finance/banking/scripts/vendor/genkgo/camt/src/Reader.php(53): Genkgo\Camt\Reader->readDom(Object(DOMDocument))
#2 /opt/company/finance/banking/scripts/vendor/genkgo/camt/src/Reader.php(77): Genkgo\Camt\Reader->readString('<?xml version="...')
#3 /opt/company/finance/banking/scripts/test.php(8): Genkgo\Camt\Reader->readFile('/mnt/company/fi...')
#4 {main}
  thrown in /opt/company/finance/banking/scripts/vendor/genkgo/camt/src/Reader.php on line 94`

the related sxd: http://www.stuzza.at/schemata/ISO.camt.053.001.02.austrian.003.xsd

**Comment by frederikbosch** [comment]
Could you explain what Stuzza is?

**Comment by sreisenb14** [comment]
Stuzza regulates the austrian baning data transfers, and also defines the standards. basically we are using the camt.053.001.02 xml files with some modifications: http://www.stuzza.at/schemata/ISO.camt.053.001.02.austrian.003.xsd


if it help's i could provide a xml file with the documents

**Comment by frederikbosch** [comment]
Use composition.

```php
<?php
class StuzzaMessageFormat implements MessageFormatInterface {
  private $camt053;
  public function __construct(Camt053\MessageFormat\V02 $camt053)
    $this->camt053;
  }

  public function getXmlNs() {
    return 'ISO:camt.053.001.02:APC:STUZZA:payments:003';
  }

   public function getMsgId() {
     return '';
   }

    public function getName() {
       return 'Stuzza';
    }

    public function getDecoder() {
      return $this->camt0530->getDecoder();
    }
}

$config = Config::getDefault();
$config->addMessageFormat(new StuzzaMessageFormat());
$reader = new Reader($config);

**Comment by frederikbosch** [comment]
Fix the namespaces yourself.

**Comment by sreisenb14** [comment]
did it, thanks!

**Comment by buzanits** [comment]
I also need to parse this format. I got the `class StuzzaMessageFormat` in the above example to work with PHP 8.2 with some modifications. But I get this error message:
```
Fatal error: Uncaught Genkgo\Camt\Exception\InvalidMessageException: Provided XML is not valid according to the XSD:
Element '{ISO:camt.053.001.02:APC:STUZZA:payments:003}Document': No matching global declaration available for the validation root.
 in /srv/www/test/camt/vendor/genkgo/camt/src/Decoder.php:44
```
I could not find anything about that in the previous issues. What's going wrong here?

**Comment by frederikbosch** [comment]
I have no idea on Stuzza, but you might want to disable [xsd validation](https://github.com/genkgo/camt#xsd-validation).
