### ISSUE TITLE
example / getting started

### ISSUE THREAD

**Issue by Kroesss** [genkgo/camt#43]
Is it possible to include a working example-file, or otherwise extend the getting-started in the readme? I cannot get it to read anything, I keep getting Fatal errors that Config and Reader are not found.

**Comment by Kroesss** [comment]
Can I ask why this is closed without any response?

**Comment by Einenlum** [comment]
@Kroesss Working example files are already present in `tests/Unit/CamtXXX/Stubs/`.
And t

**Comment by Kroesss** [comment]
@Einenlum: Okay, thanks. I have found the example-files you are referring to, but I meant an example-file of the script working (e.g. interpretting a CAMT-file and returning an array), and not an example of the CAMT-file itself. Too bad I apparantly can't use this library. Thanks for the response anyway!

**Comment by Einenlum** [comment]
@Kroesss You have an example in the readme: https://github.com/genkgo/camt#getting-started

**Comment by Kroesss** [comment]
@Einenlum: as stated in the opening-post of this thread I keep getting fatal errors when trying the example from the readme. I've tried various things, moving the files around in the folders and everything, but no luck.
I was hoping that I could get a php-file with the right includes so I could use this, since the method in the readme clearly does not work on my hosting. I have no composer or something like that, so I always use includes. In all my previous projects this has always worked, but I am guessing the "namespace" and "use"-functions only work with composer, and I cannot make an adequate translation to includes it seems.

**Comment by frederikbosch** [comment]
This package does not come with its own autoloader, and never will. You could create your own autoloader, but my advice is start using composer. Anyway, we are not going to spend time on fixing someone else's autoloading problems. It's not 2005.

**Comment by Kroesss** [comment]
@frederikbosch As you can see I had already moved on to other packages. I just clarified my situation in response on the last message from Einenlum.

On a side note, a little less hostility in the messages would be appreciated.

**Comment by frederikbosch** [comment]
@Kroesss I get your point. It is hostile from me. But the group of people that assume there is a support contract between those who create an open source package and its users is huge. Some FOSS project owners are replying to all questions. I am not that guy. I tend to [help](https://github.com/genkgo/camt/issues/41#issuecomment-268688471) [anywhere](https://github.com/genkgo/camt/issues/4) where I can, but the question has to have some substance, otherwise it will be closed. An open source package is not a class. Users should be happy with the free code they get and figure out themselves how to implement it in their systems. If features are lacking or bugs are there: I am happy to help to resolve them.

**Comment by Kroesss** [comment]
@frederikbosch I was not aware that I suggested a contract or obligation for support from you or your team in my messages. That was not my intention. It is just that calling me out as being stuck in 2005 just because I have a hosting-plan that does not support composer is a bit aggressive.

**Comment by Einenlum** [comment]
@Kroesss It can seem a bit agressive, but @frederikbosch is totally legit. It's like asking on a PHP project issues' page why your windows is so slow. Autoloading is just the norm of every PHP project for more than 10 years. You can use composer's one or others. But it does not concern the code in itself and definitely not this library.

Anyway, wish you good luck to update your host or find a custom solution ;).
