### ISSUE TITLE
Quick question about camt.054.001.04 compatibility

### ISSUE THREAD

**Issue by sdespont** [genkgo/camt#48]
Hi mainteners,

First of all, thank you for your excellent work. 

This project seems compatible with the camt.054.001.04 version due to classes, tests (and so on, ...) presents in the repo, but the "readme" page says the opposite : only the camt.054.001.02 version is compatible.

Is there any limitation to take into account about the camt.054.001.04? 

Best regards,

Sébastien

**Comment by Einenlum** [comment]
Hi @sdespont,

Thanks for your message. I am not able to test it with the `camt.054.001.04` version, so unfortunately, I'm not able to tell you if it is really compatible.

If you try could you give us feedback? If it is, we will update the Readme.

**Comment by PowerKiKi** [comment]
Readme has been updated since then to reflect latest changes in code.
