### ISSUE TITLE
Number format's decimal (camt.054.001.04) ? 

### ISSUE THREAD

**Issue by haycoin** [genkgo/camt#55]
Hi All, 
I wanted to know why into the camt.054.001.04 file amount appears under this format, with 2 decimals : 
`<Amt Ccy="CHF">5.40</Amt>
<CdtDbtInd>DBIT</CdtDbtInd>`
but the object return
`[amount:Money\Money:private] => -540`
Is there any reason ?

**Comment by frederikbosch** [comment]
See http://moneyphp.org/en/latest/.

**Comment by Samuell1** [comment]
@frederikbosch Hey, can you please add example how to add back decimals?

**Comment by Einenlum** [comment]
@Samuell1 See [here](http://moneyphp.org/en/latest/getting-started.html).
`$fiver = Money::USD(500);` in the example, means `$fiver` is a `Money` object representing `$ 5.00`.

**Comment by Samuell1** [comment]
@Einenlum Yes later i found out like there is example: http://moneyphp.org/en/latest/features/formatting.html#intl-money-formatter
