### ISSUE TITLE
DateTime parse error camt053, export from Tridos: 2017-08-09T23:59:59.999999999

### ISSUE THREAD

**Issue by sanderbeets** [genkgo/camt#56]
Hi, first of all, great lib!
Today i made an export from the Tridos Bank and it gave me this date: 

<ToDtTm>2017-08-09T23:59:59.999999999</ToDtTm>

Maybe in the $this->dateDecoder->decode we can check the format of the date before trying to parse it?
I am not familiar with all the formats of CAMT, but can we assume that the format needs to be YYYY-MM-DDTHH:II:SS ??? 
PHP can handle 6 digits for the milliseconds, but 9 are too much... 

Let me know if you have any idea / suggestions...

Kind regards,

Sander

**Comment by frederikbosch** [comment]
@sanderbeets This was fixed in the last version, see #45 for details how to get this done.
