### ISSUE TITLE
CAMT.054 Handle remittance information with unstructured AND structured data

### ISSUE THREAD

**Issue by sdespont** [genkgo/camt#58]
Regarding #37, @antlih is right : data can be loss in some cases.

Credit Suisse uses remittance information structure like this :

                <RmtInf>
                    <Ustrd>?REJECT?0</Ustrd>
                    <Strd>
                        <CdtrRefInf>
                            <Tp>
                                <CdOrPrtry>
                                    <Prtry>ISR Reference</Prtry>
                                </CdOrPrtry>
                            </Tp>
                            <Ref>333333333333333333333333334</Ref>
                        </CdtrRefInf>
                    </Strd>
                </RmtInf>
With this kind of data, `$transactionDetail->getRemittanceInformation()->getMessage();` will returns `?REJECT?0` instead of `333333333333333333333333334`.

I would suggest to use new classes in order to retrieve full and both structured and unstructured data. It would also permit to retrieve the AddtlRmtInfoption which contains information about a potential reject code from the bank.

I can develop this feature, but, it **will break the compatibility** because of getMessage() would be dropped. The data would be retrieved like this :

**ISR reference number**
`$transactionDetail->getRemittanceInformation()->getStructured()->getCreditorRefereneInformation()->getReference();`

**Additional remittance information (reject code)**
`$transactionDetail->getRemittanceInformation()->getStructured()->getAdditionalRemittanceInformation();`

**Unstructured data**
`$transactionDetail->getRemittanceInformation()->getUnStructured();`

Guys, any idea? How do you handle Credit Suisse CAMT.054 files?

**Comment by frederikbosch** [comment]
@sdespont Why you want to drop `getMessage()`? I think this feature can be created without breaking BC.

**Comment by sdespont** [comment]
@frederikbosch In the Credit Suisse example above which contains structured and unstructured blocks, what do you want to return with the `getMessage()` method? `?REJECT?0` or `333333333333333333333333334`?

As it cannot be clear what is the data to return in that case, It would more safe to force developper to chose what data he want to retrieve using `structured `and `unstructured `methods.

But yes, this feature could be added without BC but with a rule like : 

- If only `structured `block exists : `getMessage()` method returns the ISR reference
- If only `unstructured `block exists : `getMessage()` method returns the string contained in the unstructured data
- If `structured `and `unstructured `blocks exist : `getMessage()` method returns the ISR reference

What do you think about this? If you are with this concept, I will develop this feature during the next days.

**Comment by frederikbosch** [comment]
I understand what you mean with the unclearity. We want to return `?REJECT?0` for `getMessage` because that is what is returned now. Right? So current code gives precedence to unstructured over structured. Other developers will be counting on that. 

Otherwise, we could simply add methods needed.

**Comment by sdespont** [comment]
Ok, I will base the development on your suggestion. 
Thank you for your quick replies.
