### ISSUE TITLE
Readme update PHP versions or release 0.3.1

### ISSUE THREAD

**Issue by anedisi** [genkgo/camt#60]
I found the hard way that 0.3.0 is the last version compatible with php 5.6. there is no mention of that in readme.

After including Amt support myself i found this pull https://github.com/genkgo/camt/pull/44
and that its fixed in 0.4.0,

This is maybe the reason behind https://github.com/genkgo/camt/issues/46

It would be great if somebody updated the readme or released 0.3.1 with those fixes.

**Comment by sdespont** [comment]
Regarding #46, the comment "because I have some bugs" without any context neither explanation is not relevant. Furthermore, the XML file provided is valid.

**Comment by anedisi** [comment]
I agree, that was not enough for a bug report, but based on the timing of the the bug report and the fact that the his xml does not have AmtDtls but only Amt it could be that. I know that for me it was when i wanted to parse camt.054

**Comment by PowerKiKi** [comment]
Read now document the correct PHP version. And it is also enforce by composer.
