### ISSUE TITLE
composer not using most recent code

### ISSUE THREAD

**Issue by beatbesmer** [genkgo/camt#65]
i'm not sure if this issue belongs to here:
when i install your awesome "camt" with composer, the files downloaded aren't the most recent from github. i never worked with composer, so apologize if this is a luser question/report.

**Comment by Einenlum** [comment]
Hi @beatbesmer. It's because the last release (0.4.1) is 6 commits behind master.
By default, composer will fetch the last stable release if you did not precise anything. Otherwise you can require `genkgo/camt:dev-master@dev` if you need the latest changes on the repo.

**Comment by beatbesmer** [comment]
thank you @Einenlum. meanwhile i cloned the current code from github. but i'll keep your hint in mind. thank you guys for everything

**Comment by sdespont** [comment]
@Einenlum This repository is not much updated this times. May I suggest to merge waiting pull requests and create a new release?

**Comment by PowerKiKi** [comment]
@beatbesmer could you please close this issue, as it seems it your question was answered a while ago ?
