### ISSUE TITLE
TransactionDetails:Reference is array instead a single object.

### ISSUE THREAD

**Issue by beatbesmer** [genkgo/camt#68]
Hi
I followed your instructions to read the data of a single transaction.

```
$message = $reader->readFile( ...);
statements = $message->getRecords();
foreach ($statements as $statement) {
  foreach($entries as $entry) {
    $transactions=$entry->gettransactionDetails();
    foreach($transactions as $transaction) {
      $transaction <--
```
But inside the $transaction, there is this private array ([references:Genkgo\Camt\DTO\EntryTransactionDetail:private] => Array) containing reference-object(s). 

```
[references:Genkgo\Camt\DTO\EntryTransactionDetail:private] => Array
    (
      [0] => Genkgo\Camt\DTO\Reference Object
         (
            [messageId:Genkgo\Camt\DTO\Reference:private] => 
```
When i don't missunderstand the ISO20022 guidelines, the "+Account Servicer Reference (AcctSvcrRef)" is within "References (Refs)" and this record has only a 0..1 relationship.

Shouldn't there be **zero** or **one** "Reference"- Object possible? If yes, the array seems confusing, because it looks like there are several "Reference"- Objects possible. Due i'm still learning, i hope this is no missunderstanding.

Best regards
Beat

**Comment by PowerKiKi** [comment]
This is correct. Because the XSD always specifies a 0..1 relation:

```xml
<xs:element maxOccurs="1" minOccurs="0" name="Refs" type="TransactionReferences1"/>
```


 `\Genkgo\Camt\DTO\EntryTransactionDetail::$references` should be changed like so and all methods adapted:

```diff
 class EntryTransactionDetail
 {
     /**
-     * @var Reference[]
+     * @var null|Reference
      */
-    private $references = [];
+    private $reference;
     /**
      * @var RelatedParty[]
      */
```

This is a breaking change that should be made for next major version
