### ISSUE TITLE
[Feature] Write support

### ISSUE THREAD

**Issue by benjaminpick** [genkgo/camt#71]
I will develop a camt.053-File-Writer and thinking of using this project as a base. Would you be interested to merge in write support?

**Comment by tprj29** [comment]
@benjaminpick i would be interested in this. If you have it somewhere i would like to know!

**Comment by benjaminpick** [comment]
Not yet :-)

**Comment by PowerKiKi** [comment]
I'll close this as a non-issue, but feel free to continue the discussion.
