### ISSUE TITLE
determine which xml attribute to use on balances

### ISSUE THREAD

**Issue by tprj29** [genkgo/camt#72]
@frederikbosch Currently there is no way to determine which XML attribute you use when getting all available opening and closing balances. In our system this is required because one XML attribute might be more reliable then the other. Is there any change this could be implemented in future development? I could open a pull request if you like to. 

The only thing that needs to be added is a field an the DTO\Balance object named Code. Which contains the `$code = (string) $xmlBalance->Tp->CdOrPrtry->Cd;` e.g. `OPBD`

**Comment by PowerKiKi** [comment]
If this is still relevant for you, feel free to create a PR, including tests. Otherwise I suppose you can close the issue.

**Comment by tprj29** [comment]
I fixed this myself.
