### ISSUE TITLE
Replace deprecated dependency 

### ISSUE THREAD

**Issue by D4rkMindz** [genkgo/camt#75]
The dependency [jschaedl/iban](https://github.com/jschaedl/iban) is marked as deprecated. Replace it with [jschaedl/iban-validation](https://github.com/jschaedl/iban-validation). The library jschaedl/iban-validation does require PHP >= 7.1.3, but as far as i can see, there should not be a problem with this.

**Comment by D4rkMindz** [comment]
Duplicate of #74

**Comment by PowerKiKi** [comment]
Solved in #74
