### ISSUE TITLE
Update maintainers

### ISSUE THREAD

**Issue by Einenlum** [genkgo/camt#77]
Hi @frederikbosch,

I unfortunately don't have time anymore to work on this project. Could it be possible to remove my rights on it?

Thanks for your work! :)

**Comment by hanishsingla** [comment]
Hi @Einenlum and @frederikbosch 

I see that many pull requests are pending for this project. Is there anyone maintaining new changes?

We can work on issues, provided pull requests are merged. 

Thanks for your work

**Comment by frederikbosch** [comment]
I'll do some updates and fixes this week

**Comment by PowerKiKi** [comment]
I'm considering using this lib in one of our project and would be reassured if there were a bit more activity on the PR and issues. At a glance I saw some quality PR and closable issues that could be dealt with relatively easily.

Maybe you could consider adding a new contributor to it if you don't have much time available for it ?

**Comment by PowerKiKi** [comment]
@hanishsingla I noticed you forked this repo very recently and merged all open PR. Would you be interested instead in joining this repo as a collaborator (assuming @frederikbosch agree) ?

**Comment by frederikbosch** [comment]
@Einenlum Thank you very much for all your contributions. We have quite some CAMT standards that we support right now.

@PowerKiKi I am more than happy to hand over some responsibility. I made you with @hanishsingla collaborator of the repo.

**Comment by frederikbosch** [comment]
@PowerKiKi @hanishsingla Hopefully you/we can update the library to finish all the outstanding issues.

**Comment by PowerKiKi** [comment]
Great ! I wasn't necessarily expected to be added to the project myself, but I'll see what I can do in the coming days.

Thanks for the quick reply.

**Comment by hanishsingla** [comment]
@frederikbosch .. Thanks for adding me as a collaborator. 

I had forked and published this repo in another name for some urgent issues. I will merge the PRs and contribute as much I can.

**Comment by tijuan** [comment]
Hi there, 

cool to hear that something is happening here.

I also have my own fork (on Bitbucket)  as the project did not get the needed support (which is understandable - no blame), especially this requested feature that I worked on https://github.com/genkgo/camt/pull/70

I may have to work on this component again very soon and would be happy to contribute here if something would be missing

Thanks @frederikbosch for opening the project

Regards,
