### ISSUE TITLE
Drop PHP 7.0 support ?

### ISSUE THREAD

**Issue by PowerKiKi** [genkgo/camt#78]
I would like to drop support of PHP 7.0 in our next major version (1.0.0) because it reached end of life 3 months ago, prevent us to integrate phpstan properly in our workflow and prevent us from type hinting nullable types and just add overhead to the general maintenance.

The idea being that for users who are still on PHP 7.0, they can use the freshly released camt 0.6.0.

@frederikbosch, @sdespont, @jarnovanleeuwen any thoughts on that ?

**Comment by sdespont** [comment]
@PowerKiKi No problem for me, I fully support to drop PHP versions which are no longer actively supported if needed.

**Comment by frederikbosch** [comment]
@PowerKiKi I'd definitely upgrade. In other libraries I use the following two rules, both related to the [PHP support table](https://www.php.net/supported-versions.php). 

1. If PHP actively supports a version, we must too.
2. If PHP only provides security releases, there must be *a* version available of the library for that PHP version.

Hence, for this library I'd upgrade to PHP 7.2, and have version 0.6 available for those on PHP 7.0/7.1.

**Comment by jarnovanleeuwen** [comment]
I'm also positive about this change, for the reasons stated above.
