### ISSUE TITLE
Fatal error:Uncaught InvalidArgumentException: Unknown IBAN (can parse continue?)

### ISSUE THREAD

**Issue by MrMoronIV** [genkgo/camt#81]
Continuing on the ABN Amro example file, they put an incorrect IBAN in their example file: 
```
<b>Fatal error</b>:  Uncaught InvalidArgumentException: Unknown IBAN NL46ABNA0499998748
```

Is there a way to continue the import when this happens for one transaction or is this an edge case that never happens IRL and should I give up on the ABN Amro example file mentioned in my previous (closed) issue?

**Comment by PowerKiKi** [comment]
If the document has an invalid structure or contains invalid data, then it cannot be read at all. We use https://github.com/globalcitizen/php-iban to validate IBAN. If you believe your IBAN actually is valid you might want to report an a but over there, but most likely it's just random data.

This might help you for testing purpose: http://randomiban.com/?country=Netherlands
