### ISSUE TITLE
[camt.053] RelatedAgent BIC

### ISSUE THREAD

**Issue by zembrowski** [genkgo/camt#83]
The xml tag for the RelatedAgents BIC is named in camt.053(.001.04) "BICFI".

I noticed, that camt.052 uses a "BIC" xml tag and is being tested with unit tests. For camt.053 an empty string is getting returned, as there is no "BIC" and no unit test. Is there a quick way to retrieve the BICFI for camt.053?

Thanks in advance for your response.

**Comment by PowerKiKi** [comment]
I don't think there is any way to get BICFI with current code.

I would suggest you to submit a new PR that adds an abstract method `\Genkgo\Camt\Decoder\EntryTransactionDetail::getBIC` that is implemented as needed in each inheriting classes according to CAMT version. Or alternatively implement the most common version in the parent class and override only in the rare cases that differ.

And then of course use that new method in `addRelatedAgents`.

If you cover all of that with unit tests, I'll merge you PR (after reviews of course).
