### ISSUE TITLE
How to get Debtor (company/private) identification number?

### ISSUE THREAD

**Issue by orukaz** [genkgo/camt#85]
How to get Debtor (company/private) identification number?

![Screenshot 2019-12-29 at 17 06 36](https://user-images.githubusercontent.com/33488045/71558602-ed502880-2a5d-11ea-9c90-861fbb1f374c.png)

![Screenshot 2019-12-29 at 17 08 51](https://user-images.githubusercontent.com/33488045/71558613-08229d00-2a5e-11ea-8d82-5649db5812c1.png)

I looked the code and I didn't find methods and attributes for that - it would be very useful feature to identify company or private person transaction with identification number not only names or bank accounts.

Maybe Debtor or even Creditor class can be complemented with additional methods to get private and organisation ID.

**Comment by PowerKiKi** [comment]
AFAIK there is now way to get this for now. If you submit a PR, including tests, it could be merged
