### ISSUE TITLE
Entry details: retrieve "Batch" details

### ISSUE THREAD

**Issue by nssnl** [genkgo/camt#86]
I'm trying to get `PmtInfId` and `NbOfTxs` within the `Btch` of the entry details. See example piece of the XML below.

```
<NtryDtls>
	<Btch>
		<PmtInfId>PI REFERENCE-EXAMPLE</PmtInfId>
		<NbOfTxs>8</NbOfTxs>
	</Btch>
</NtryDtls>
```
I'm using the (simplified) code below to retrieve the relevant info such as amount, date, iban and transaction details.
```$message = $reader->readFile($xml_file);
$statements = $message->getRecords();
foreach ($statements as $statement) {
	$entries = $statement->getEntries();
	foreach ($entries as $entry) {
		$details = $entry->getTransactionDetails();
		foreach ($details as $detail) {
		// ....
		}
	}
}
```
Is there any way to retrieve `PmtInfId` and `NbOfTxs` within the `Btch`? Thanks

**Comment by PowerKiKi** [comment]
You might be looking for `\Genkgo\Camt\DTO\Entry::getBatchPaymentId()` which seems to be doing what you ask for
