### ISSUE TITLE
getRemittanceInformation() throws error

### ISSUE THREAD

**Issue by BertHankes** [genkgo/camt#87]
When reading a Camt053 xml (ABN-AMRO) I get error messages when I use getRemittanceInformation().
It seems that ABN-AMRO does not always include the RemittanceInformation in the XML.

I have disabled line 163 of genkgo/camt/src/DTO/EntryTransactionDetail.php and now I can read the XML.

Is ABN-AMRO to blame for this?

**Comment by PowerKiKi** [comment]
Try to upgrade to [1.0.0](https://github.com/genkgo/camt/releases/tag/1.0.0), it should not be too much work, and should work out of the box.
