### ISSUE TITLE
Amount decimal point ignored

### ISSUE THREAD

**Issue by axelhuizinga** [genkgo/camt#94]
Parsing a camt.052.001.02 file seems to ignore the decimal point when parsing the amounts.
For example <Amt>65.50</Amt> accessed with Entry->getAmount()->getAmount() prints -6550 
Minus is correct since it are returned bookings but where got the decimal point lost?

**Comment by PowerKiKi** [comment]
This is by design. See https://github.com/genkgo/camt/issues/93#issuecomment-708951687
