### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by onlime** [genkgo/camt#95]
Ist there PHP 8.0 support in the works? Can I help you testing?

Best regards,
Philip

**Comment by PowerKiKi** [comment]
This is blocked by https://github.com/moneyphp/money/issues/619 and https://github.com/jschaedl/iban-validation/pull/53. If you want to help, you should start by helping them.

**Comment by PowerKiKi** [comment]
Follow #97 for PHP 8.0 support
