### ISSUE TITLE
Wrong formatting of JPY

### ISSUE THREAD

**Issue by ghostika** [genkgo/camt#98]
I have a camt file with the JPY currency. I've seen the other issue regarding of the deciaml issue. 
My problem is, JPY has no decimal places.  
The following balance entry:

```
<Bal>
    <Tp>
        <CdOrPrtry>
            <Cd>CLBD</Cd>
        </CdOrPrtry>
    </Tp>
    <Amt Ccy="JPY">27</Amt>
    <CdtDbtInd>CRDT</CdtDbtInd>
    <Dt>
        <Dt>2020-02-20</Dt>
    </Dt>
</Bal>
```

is parsed to 
```
^ Money\Money^ {#135
  -amount: "2700"
  -currency: Money\Currency^ {#209
    -code: "JPY"
  }
}
```

And if I want to format this with money's  DecimalFormatter (what in any other case works), then I get as formatted value `JPY 2700`, what is wrong.  
The only thing I can do now is to divide it with 100, if it's JPY.

**Comment by PowerKiKi** [comment]
This is reproducible. We use a custom parser, `\Genkgo\Camt\Util\StringToUnits::convert()`, which incorrectly ignore the currency. I believe our custom class should be entirely replaced with calls to `\Money\Parser\DecimalMoneyParser` instead.

Could you please create a PR for that ? Delete `StringToUnits` entirely and replace calls with `DecimalMoneyParser` ?

**Comment by ghostika** [comment]
Yes, I will take a look at it at the weekend. Which way would you prefer, should I create an instance of it in the constructors or in the functions, where we need it?

**Comment by PowerKiKi** [comment]
I am not quite sure, but I suppose creating an instance in constructor would make sense if it's used "often" in various methods...
